TransactiveEnergy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
    path('user/', include('apps.users.urls')),
    path('device/', include('apps.devices.urls')),
]

apps/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('dashboard/', views.dashboard, name='dashboard'),
  path('dashboard/update/', views.update_dashboard_state, name='update_dashboard_state'),
  path('operator/', views.admin, name='admin'),
  path('operator/new_device', views.CreateNewDevice, name='new_device'),
  path('operator/update_device/<str:uuid>', views.UpdateDevice, name='update_device'),
  path('operator/delete_device/<str:uuid>', views.DeleteDevice, name='delete_device'),
  path('webcam/feed/', views.WebcamStreamTest, name='webcam_feed'),
  path('webcam/stream/', views.WebcamStreamTestPage, name='webcam_stream'),
]

apps/dashboard/models.py
from django.db import models

# Create your models here.
class ComedPriceData(models.Model):
  timestamp = models.DateTimeField(primary_key=True, unique=True)
  price = models.FloatField(default=0.0)

  def __str__(self):
    return f'ComEd: {self.timestamp} - {self.price} / kWh'
  
class UbibotSensorTemp(models.Model):
  timestamp = models.DateTimeField(primary_key=True, unique=True)
  temp = models.FloatField(default=-1.0)

  def __str__(self):
    return f'TempSensor: {self.timestamp} - {self.temp} deg F'

apps/devices/models.py
from django.db import models
import uuid

# Create your models here.

# Generic model for a device -- can be extended to include more specific device types
class Device(models.Model):
  DEVICE_TYPES = [
    ('generic', 'Generic Device'),
    ('kasa_switch', 'Kasa Switch'),
    ('fridge', 'Fridge'),
  ]

  uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(max_length=100, default='NewGenericDevice', null=True, blank=True)
  type = models.CharField(max_length=20, choices=DEVICE_TYPES, default='generic')
  description = models.TextField(null=True, blank=True)
  status = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  # Fields to be used for ADR
  adr_enabled = models.BooleanField(default=False)
  use_user_window = models.BooleanField(default=False)
  on_window_begin = models.TimeField(null=True, blank=True)
  on_window_end = models.TimeField(null=True, blank=True)
  off_window_begin = models.TimeField(null=True, blank=True)
  off_window_end = models.TimeField(null=True, blank=True)

  critical_load = models.BooleanField(default=False)

  def __str__(self):
    return f'{self.uuid}.{self.type}.{self.name}'

# Model for KasaSwitches
class KasaSwitch(models.Model):
  device = models.OneToOneField(Device, on_delete=models.CASCADE, primary_key=True)
  ip_address = models.GenericIPAddressField()

  def __str__(self):
    return f'{self.device.uuid}.{self.device.type}.{self.device.name}'
  
# Model for the fridge
class Fridge(models.Model):
  device = models.OneToOneField(Device, on_delete=models.CASCADE, primary_key=True)
  high_temp_threshold = models.FloatField(default=50.0)
  low_temp_threshold = models.FloatField(default=20.0)
  target_temp_threshold = models.FloatField(default=38.0)
  

  def __str__(self):
    return f'{self.device.uuid}.{self.device.type}.{self.device.name}'
  
# Model for energy consumption storage
class EnergyConsumption(models.Model):
  label = models.CharField(max_length=100, default='Unspecified')
  timestamp = models.DateTimeField(default=None)
  energy_consumed = models.FloatField(default=0.0)

  def __str__(self):
    return f'{self.label}.{self.timestamp} -- {self.energy_consumed}watt'

apps/dashboard/forms.py
from django import forms
from django.forms import ModelForm

from apps.devices.models import Device, KasaSwitch, Fridge

class DeviceForm(ModelForm):
  kasa_ipv4 = forms.GenericIPAddressField(required=False, label='kasa_ipv4')
  
  class Meta:
    model = Device
    fields = ['name', 'description', 'type', 'status', 'critical_load', 'adr_enabled']

class DeviceUpdateForm(forms.ModelForm):
  kasa_ipv4 = forms.GenericIPAddressField(required=False, label="IPv4 Address")

  class Meta:
    model = Device
    fields = ['name', 'type', 'description', 'status', 'critical_load', 'adr_enabled', 'use_user_window', 'on_window_begin', 'on_window_end', 'off_window_begin', 'off_window_end']
    widgets = {
      'on_window_begin': forms.TimeInput(attrs={'type': 'time', 'class':'form-control'}),
      'on_window_end': forms.TimeInput(attrs={'type': 'time', 'class':'form-control'}),
      'off_window_begin': forms.TimeInput(attrs={'type': 'time', 'class':'form-control'}),
      'off_window_end': forms.TimeInput(attrs={'type': 'time', 'class':'form-control'}), 
    }

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    # Hide IPv4 field unless it's a KasaSwitch
    if self.instance and self.instance.type != 'kasa_switch':
        self.fields.pop('ipv4', None)

apps/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from apps.devices.models import Device, KasaSwitch, Fridge
from apps.dashboard.battery_management import estimate_remaining_time
from .forms import DeviceForm, DeviceUpdateForm

import cv2
from django.http import StreamingHttpResponse, JsonResponse

from django.db.models import OuterRef, Subquery, Value, CharField
from django.db.models.functions import Coalesce

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import requests
import json
from datetime import datetime, timedelta, timezone

from .models import ComedPriceData, UbibotSensorTemp

import os
import dotenv

from .battery_management import update_battery

# Create your views here.
def home(request):
  return render(request, 'home.html')

def fetch_comed_data(previous_days):
  ''' Fetch previous_days worth of 5-minute pricing data from ComEd (from now to now - previous_days). 
  Store the data in the db.sqlite db, delete any data older than now - current_days.

  Args:
    previous_days (int): number of previous days from now to get data for
  
  Returns:
    None: Performs query and stores data in DB  
  '''

  # Create datetime objects for window start and end
  end_date_obj = datetime.now(timezone.utc)
  begin_date_obj = datetime.now(timezone.utc) - timedelta(days=previous_days)

  # See if most recent entry is older than end of needed window
  query_end_date = end_date_obj.strftime('%Y%m%d%H%M')

  latest_entry = ComedPriceData.objects.latest('timestamp')

  # TODO: Check if we need to query ComEd at all, don't query if its not necessary

  if latest_entry.timestamp > begin_date_obj:
    query_begin_date = latest_entry.timestamp.strftime('%Y%m%d%H%M')
  else:
    query_begin_date = begin_date_obj.strftime('%Y%m%d%H%M')

  print(f'Querying comed from {query_begin_date} to {query_end_date}')

  url = f'https://hourlypricing.comed.com/api?type=5minutefeed&datestart={query_begin_date}&dateend={query_end_date}'
  response = requests.get(url)
  if response.status_code != 200:
    print('Unable to get pricing data from ComEd')
    return
  
  data = response.json()
  n_saved = 0
  for d in data:
    try:
      timestamp = datetime.fromtimestamp(int(d['millisUTC']) / 1000, timezone.utc)
    except (ValueError, TypeError):
      raise RuntimeError('Could not convert timestamp from comed')
    try:
      price = float(d['price'])
    except (ValueError, TypeError):
      price = -1.0

    new_db_obj = ComedPriceData(
      timestamp = timestamp,
      price = price
    )

    new_db_obj.save()
    n_saved += 1
  
  print(f'Saved {n_saved} new price data objects to DB')

  # Delete all entries with timestamp less than beginning of window
  num_deleted, _ = ComedPriceData.objects.filter(
    timestamp__lt=begin_date_obj
  ).delete()

  print(f'Deleted {num_deleted} ComedPriceData objects older than {begin_date_obj}')

def get_temp():
  ''' Get temperature reading from UbiBot sensor in the fridge

  Args:
    None
  Returns:
    None: Stores temp value in db.sqlite
  '''

  dotenv.load_dotenv()

  # Get secrets from env vars
  api_key = os.getenv('UBIBOT_API_KEY')
  api_channel = os.getenv('UBIBOT_CHANNEL')

  url = f'https://api.ubibot.com/channels/42895?account_key=54183910b6a04fd59648e022d58a1229'
  response = requests.get(url)

  if response != 200:
    print('Error fetching temperature from Ubibot API')
    return
  
  data = response.json()

  # Get temp from JSON. Temp value is in celcius
  temp = data['channel']['last_values']['field1']['value']
  temp = (temp * 9/5) + 32.0

  print(f'Fetched temp value of {temp} from UbiBot API')

  new_temp_obj = UbibotSensorTemp(
    temp = temp
  )

  new_temp_obj.save()

  return temp
  

def dashboard(request):
  weekly_load_url = f'http://192.168.0.111/query?select=[time.iso,input_0,Fridge,Solar,Recepticles]&begin=s-7d&end=s&group=15m&format=json&header=yes'
  response = requests.get(weekly_load_url)
  if response.status_code != 200:
    print('Error fetching weekly data from IotaWatt')
    return JsonResponse({'error': 'Error fetching weekly data from IotaWatt'}, status=500)
  
  weekly_data = response.json().get('data', [])

  if not weekly_data:
    print('No weekly data returned from IotaWatt')
    return JsonResponse({'error': 'Error fetching weekly data from IotaWatt'}, status=500)

  system_weekly_load = []
  weekly_load_labels = []

  for wd in weekly_data:
    date_obj = datetime.fromisoformat(wd[0])
    weekly_load_labels.append(date_obj.strftime('%d %b %Y'))

    try:
      fridge = float(wd[2])
    except (ValueError, TypeError):
      fridge = 0.0
    
    try:
      recepticles = float(wd[4])
    except (ValueError, TypeError):
      recepticles = 0.0

    system_weekly_load.append(fridge + recepticles)
  
  fetch_comed_data(3)

  weekly_price_labels = []
  weekly_price_data = []

  comed_price_objects = ComedPriceData.objects.filter(
    timestamp__gt=datetime.now(timezone.utc) - timedelta(days=3)
  )

  for cpo in comed_price_objects:
    weekly_price_labels.append(cpo.timestamp.strftime('%d %b %y - %H:%S'))
    weekly_price_data.append(cpo.price)

  context = {
    'weeklyLoadLabels': json.dumps(weekly_load_labels),
    'weeklyLoadData': json.dumps(system_weekly_load),
    'weeklyPriceLabels': json.dumps(weekly_price_labels),
    'weeklyPriceData': json.dumps(weekly_price_data)
  }

  return render(request, 'dashboard.html', context)

def update_dashboard_state(request):
  battery_percentage = 100
  estimated_time = 3.1

  url = f'http://192.168.0.111/query?select=[time.iso,input_0,Fridge,Solar,Recepticles]&begin=s-5s&end=s&group=5s&format=json&header=yes'
  response = requests.get(url)
  if response.status_code != 200:
    print('Error fetching data from IotaWatt')
    return JsonResponse({'error': 'Error fetching data from IotaWatt'}, status=500)

  data = response.json().get('data', [])

  if not data:
    print('No data returned from IotaWatt')
    return JsonResponse({'error': 'Error fetching data from IotaWatt'}, status=500)
  
  for d in data:
    try:
      fridge = float(d[2])
    except (ValueError, TypeError):
      fridge = 0.0
    
    try:
      battery = float(d[3])
    except (ValueError, TypeError):
      battery = 0.0
    
    try: 
      recepticles = float(d[4])
    except (ValueError, TypeError):
      recepticles = 0.0

    break

  if battery >= 1.0:
    power_source = 'Battery'
    # # Start the battery drain sim
    # if battery_time_start == None:
    #   battery_time_start = datetime.now(timezone.utc)
    # battery_percentage, estimated_time = update_battery(battery_time_start)
  else:
    power_source = 'Grid'
    # Restart battery time tracking
    # battery_time_start = None

  # fridge_temp = get_temp()
  fridge_temp = 47.75

  new_state = {
    'system_current_power': fridge + recepticles,
    'critical_load_current_power': recepticles,
    'fridge_current_power': fridge,
    'fridge_current_temp': fridge_temp,
    'device_states': {},
    'battery_current_power': battery,
    'battery_charge': int(battery_percentage),
    'battery_remaining_time': float(estimated_time),
    'power_source': power_source,
  }

  return JsonResponse(new_state)

@login_required()
def admin(request):
  devices = Device.objects.all().annotate(
    ipv4=Coalesce(
        Subquery(
            KasaSwitch.objects.filter(device=OuterRef('pk')).values('ip_address')[:1],
            output_field=CharField()
        ),
        Value("N/A", output_field=CharField())
    )
  ).order_by('name')
  context = {'devices': devices}
  return render(request, 'admin.html', context)

@login_required()
def CreateNewDevice(request):
  form = DeviceForm()

  if request.method == 'POST':
    form = DeviceForm(request.POST)
    if form.is_valid():
      device = form.save()
      if device.type == 'kasa_switch':
        ip_address = request.POST.get('kasa_ipv4', '').strip()
        if ip_address:
          KasaSwitch.objects.create(device=device, ip_address=ip_address)
        else:
          KasaSwitch.objects.create(device=device, ip_address='0.0.0.0')
      
      return redirect('admin')
    
  context = {'form': form}
  return render(request, 'new_device.html', context)

@login_required()
def UpdateDevice(request, uuid):
  device = Device.objects.get(uuid=uuid)
  form = DeviceUpdateForm(instance=device)
  ipv4_address = None

  if device.type == 'kasa_switch':
    kasa_switch = KasaSwitch.objects.filter(device=device).first()
    if kasa_switch:
      ipv4_address = kasa_switch.ip_address

  if request.method == 'POST':
    form = DeviceUpdateForm(request.POST, instance=device)
    if form.is_valid():
      modified_fields = []
      
      for field in form.changed_data:
        if field in ['use_user_window', 'on_window_begin', 'on_window_end']:
          modified_fields.append(field)
      
      if modified_fields:
        form.save(commit=False)
        device.save(update_fields=modified_fields)
      else:
        form.save()
      
      if device.type == 'kasa_switch':
        new_ip = request.POST.get('kasa-ipv4', '').strip()
        if kasa_switch:
          kasa_switch.ip_address = new_ip
          kasa_switch.save()
        else:
          KasaSwitch.objects.create(device=device, ip_address=new_ip)

      return redirect('admin')
     
  context = {'form': form, 'ipv4_address': ipv4_address}
  return render(request, 'update_device.html', context)

@login_required
def DeleteDevice(request, uuid):
  device = Device.objects.get(uuid=uuid)
  context = {'device_name': device.name, 'device_id': uuid}

  if request.method == 'POST':
    if device.type == 'kasa_switch':
      kasa_switch = KasaSwitch.objects.filter(device=device).first()
      kasa_switch.delete()

    device.delete()
    return redirect('admin')
  
  return render(request, 'delete_device.html', context)

camera = None
for i in range(1):
  camera = cv2.VideoCapture(i)
  if camera.isOpened():

apps/dashboard/templates/admin.html
{% extends "base.html" %}
{% block title %}Operator Panel{% endblock %}
{% block content %}

<h1 class="tomorrow-medium">Operator Panel</h1>
<div class="row">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Device Name</th>
          <th>Device Type</th>
          <th>Device Status</th>
          <th>Crit Load</th>
          <th>ADR</th>
          <th>IPv4</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for device in devices %}
        <tr>
          <td>{{ device.name }}</td>
          <td>{{ device.type }}</td>
          {% if device.status %}
            <td><i class="fa-solid fa-circle" style="color: #007800"></i></td>  <!-- Green check icon -->
          {% else %}
            <td><i class="fa-solid fa-circle text-red-500" style="color:red"></i></td>  <!-- Red cross icon -->
          {% endif %}
          {% if device.critical_load %}
            <td><i class="fa-regular fa-circle-check" style="color:#007800"></i></td>
          {% else %}
            <td><i class="fa-regular fa-times-circle"></i></td>
          {% endif %}
          {% if device.adr_enabled %}
            <td><i class="fa-regular fa-circle-check" style="color:#007800"></i></td>
          {% else %}
            <td><i class="fa-regular fa-times-circle"></i></td>
          {% endif %}
          {% if device.type == 'kasa_switch' %}<td>{{ device.ipv4 }}</td> {% else %}<td>N/A</td>{% endif %}
          <td>
          {% if device.type == 'kasa_switch' %}
            <a href="{% url 'kasa_switch_on' device.uuid %}" class="btn btn-success bg-curent-green">On</a>
            <a href="{% url 'kasa_switch_off' device.uuid %}" class="btn btn-success bg-curent-green">Off</a>
          {% elif device.type == 'fridge' %}
            <a href="{% url 'fridge_on' device.uuid %}" class="btn btn-success bg-curent-green">On</a>
            <a href="{% url 'fridge_off' device.uuid %}" class="btn btn-success bg-curent-green">Off</a>
            
          {% else %}
            <a href="#" class="btn btn-success bg-curent-green disabled">On</a>
            <a href="#" class="btn btn-success bg-curent-green disabled">Off</a>
          {% endif %}
            <a href="{% url 'update_device' device.uuid %}" class="btn btn-success bg-curent-green">Edit</a>
            <a href="{% url 'delete_device' device.uuid %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col">
    <a href="{% url 'new_device' %}" class="btn btn-success bg-curent-green">Add New Device</a>
  </div>
</div>
{% endblock %}

apps/dashboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>{% block title %}{% endblock %}Transactive Energy</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'CURENT_Logo_Primary.png' %}" type="image/x-icon">

    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'colors.css' %}">
    <link rel="stylesheet" href="{% static 'fonts.css' %}">

    <!-- Google Fonts: Tomorrow-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tomorrow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
 
    <!-- FontAwesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    {% block extra_head %}{% endblock %}
      
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-curent-green">
      <div class="container-fluid">
        <a class="navbar-brand tomorrow-medium" href="#">
          <img src="{% static 'CURENT_primary_inverted.png' %}" alt="Transactive Energy" width="30" height="30" class="d-inline-block align-text-center">
          Transactive Energy
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin' %}">Operator Panel</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webcam_stream' %}">Webcam Stream</a>
          </ul>
        </div>
        {% if request.user.is_authenticated %}
        <span class="text-white">Hello, {{ request.user }} </span>
        <span><a href="{% url 'logout' %}" class="btn btn-curent-green-alt mx-2">Logout</a></span>
        {% else %}
        <span><a href="{% url 'login' %}" class="btn btn-primary bg-primary">Login</a></span>
        {% endif %}
      </div>
    </nav>
   
    <div class="container">{% block content %} {% endblock %}</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

apps/dashboard/templates/delete_device.html
{% extends "base.html" %}
{% block title %}Confirm Delete | {% endblock %}
{% block content %}
<div class="row mt-5">
  <div class="col-md-12">
    <h4 class="tomorrow-medium bg-danger text-center">WARNING</h4>
  </div>
  <div class="col-md-12">
    <p class="text-center">Are you sure you want to delete "{{ device_name }}"?</p>
  </div>
</div>
<div class="d-flex align-items-center flex-column my-2">
  <form method="POST" action="{% url 'delete_device' device_id %}">
    {% csrf_token %}
    <a href="{% url 'admin' %}" class="btn btn-success bg-curent-green">Cancel</a>
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</div>



{% endblock %}

apps/dashboard/templates/home.html
{% extends "base.html" %} 
{% block title %} Home Page {% endblock %}
{% block content %}
<p>This is the home page</p>
{% endblock %}

apps/dashboard/templates/new_device.html
{% extends "base.html" %}
{% block title %}Create New Device{% endblock %}
{% block content %}
<h1>Create New Device</h1>

<form method="POST" action="">
  {% csrf_token %}
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    {{ form.name }}
  </div>
  
  <div class="mb-3">
    <label for="type" class="form-label">Type</label>
    {{ form.type }}
  </div>
  
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    {{ form.description }}
  </div>
  
  <div class="mb-3">
    <label for="status" class="form-label">Status</label>
    {{ form.status }}
  </div>

  <div class="mb-3">
    <label for="critical_load" class="form-label">Is this device a critical load?</label>
    {{ form.critical_load }}
  </div>
  
  <div id="kasa-options" class="mb-3" style="display: none;">
    <label for="kasa_ipv4">IPv4</label>
    <input type="text" name="kasa_ipv4" id="kasa_ipv4"> 
  </div>

  <button type="submit" class="btn btn-primary bg-curent-green">Create Device</button>
</form>

<script>
  document.addEventListener("DOMContentLoaded", function() {
      let typeField = document.querySelector("#id_type");
      let kasaOptions = document.querySelector("#kasa-options");
  
      function toggleKasaOptions() {
          if (typeField.value === "kasa_switch") {
              kasaOptions.style.display = "block";
          } else {
              kasaOptions.style.display = "none";
          }
      }
  
      // Run on page load (if editing an existing device)
      toggleKasaOptions();
  
      // Listen for changes
      typeField.addEventListener("change", toggleKasaOptions);
  });
</script>

{% endblock %}

apps/dashboard/templates/stream_test.html
{% extends "base.html" %}
{% block title %}Webcam Feed{% endblock %}
{% block content %}
<div class="container py-4">
  <h1 class="tomorrow-medium text-center">Live Webcam Stream</h1>
  <div class="embed-responsive embed-responsive-16by9">
    <img src="{% url 'webcam_feed' %}" width="auto" height="auto" class="mx-auto d-block embed-responsive-item" alt="Webcam Feed">
  </div>
</div>

{% endblock %}

apps/dashboard/templates/update_device.html
{% extends "base.html" %}
{% block title %}Update Device{% endblock %}
{% block content %}

<div class="row">
  <div class="col">
    <h1 class="text-center">{{ device_name }}</h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <form method="POST" action="">
      {% csrf_token %}
      <div class="mb-3">
        <label for="name" class="form-label">Device Name</label>
        {{ form.name }}
      </div>

      <div class="mb-3">
        <label for="type" class="form-label">Device Type</label>
        {{ form.type }}
      </div>
      
      <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        {{ form.description }}
      </div>

      <div class="mb-3">
        <label for="status" class="form-label">Device Status</label>
        {{ form.status }}
      </div>

      <div class="mb-3">
        <label for="critical_load" class="form-label">Is this device a critical load?</label>
        {{ form.critical_load }}
      </div>

      <div class="mb-3" id="kasa-ipv4-field" style="display: none">
        <label for="kasa-ipv4" class="form-label">Kasa IPv4</label>
        <input type="text" name="kasa-ipv4" id="id_ipv4" value="{{ ipv4_address|default:'' }}">
      </div>

      <hr>
      <div class="mb-3">
        <h4>ADR Parameters</h4>
      </div>
      <div class="mb-3">
        <label for="adr_enabled" class="form-label">Enable ADR</label>
        {{ form.adr_enabled }}
      </div>
      <div class="mb-3">
        <label for="use_user_window" class="form-label">Use manually specified on windows?</label>
        {{ form.use_user_window }}
      </div>
      <div class="mb-3">
        <label for="on_window_begin" class="form-label">On-Window Beginning</label>
        {{ form.on_window_begin }}
      </div>
      <div class="mb-3">
        <label for="on_window_end" class="form-label">On-Window Ending</label>
        {{ form.on_window_end }}
      </div>
      <div class="mb-3" style="display: none">
        <label for="off_window_begin" class="form-label">Off-Window Beginning</label>
        {{ form.off_window_begin }}
      </div>
      <div class="mb-3" style="display: none">
        <label for="off_window_end" class="form-label">Off-Window Ending</label>
        {{ form.off_window_end }}
      </div>

      <button type="submit" class="btn btn-primary bg-curent-green">Save</button>
    </form>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    let dropdown = document.querySelector("[name=type]");
    let kasa_ipv4_field = document.getElementById("kasa-ipv4-field");

    function toggleKasaIPField() {
      if (dropdown.value === "kasa_switch") {
        kasa_ipv4_field.style.display = "block";
      } else {
        kasa_ipv4_field.style.display = "none";
      }
    }

    // Run on page load since we'll have a pre-selected field
    toggleKasaIPField()

    dropdown.addEventListener("change", toggleKasaIPField);
  })
</script>

{% endblock %}